# Site settings
title: Transilience Tech
description: 'People First | Technology Always'
url: 'https://www.transilience.tech'
baseurl: ''
profilepic: '/images/logo.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-173268091-1
font_awesome: '53d7a3a62b.js'

author:
  name: 'Transilience Tech LLP'
  email: contact@transilience.tech
  twitter_username: _transilience
  github_username: transilience
  linkedin_username: transilience-tech-5850231aa
  linkedin_page: transilience-tech-llp
  meetup_name: 
  quora: Transilience-Tech

blog:
  default_img: '/images/post_images/default.jpg'
  
other_urls:
  # blog: https://medium.com/@transiliencetech
  blog: '/blog'
  
# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']

collections:
  authors:
    output: true

plugins:
  - jekyll-sitemap